#!/usr/bin/env bash
set -e

ALL_PROJECTS=( \
	"http-api" \
	"tripsit-discord-bot" \
)

DOCKER_COMPOSE_PROJECT_IDS=( \
	"http-api" \
)

ROOT_PATH="$(dirname "${0}")"
CONFIG_PATH="${ROOT_PATH}/config"
SCRIPTS_PATH="${ROOT_PATH}/scripts"
LIB_PATH="${SCRIPTS_PATH}/lib"
REPOS_PATH="${ROOT_PATH}/repos"

function usage {
	cat << EUSAGE
usage: ./tsctl <command>

commands:
	bootstrap	Clones all git repos down and installs their dependencies
	up			Starts all docker containers
	test		Runs automated tests for repositories
	clean		Removes and reinstalls all artifacts
	chkenv		Ensures local environment has dependencies installed
EUSAGE
}

command_arg="${1}"
if [[ "${1}" =~ /tsctl$/ ]]; then
    command_arg="${2}"
fi

case "${command_arg}" in
	"bootstrap" | "up" | "test" | "clean "| "chkenv")
		source "${SCRIPTS_PATH}/${command_arg}.sh"
		;;
	"--help" | "-h")
		usage
		;;
	*)
		>&2 echo "Command not found '${command_arg}'"
		usage
		exit 1
esac
