#!/usr/bin/env bash
set -e

ALL_PROJECTS=( \
	"main-website" \
	"api" \
	"database" \
)

ROOT_PATH="$(dirname "${0}")"
SCRIPTS_PATH="${ROOT_PATH}/scripts"
LIB_PATH="${SCRIPTS_PATH}/lib"
REPOS_PATH="${ROOT_PATH}/repos"

function usage {
	cat << EUSAGE
usage: ./tsctl <command>

commands:
	bootstrap	Clones all git repos down and installs their dependencies
	test		Runs automated tests for repositories
	clean		Removes and reinstalls all artifacts
	chkenv		Ensures local environment has dependencies installed
EUSAGE
}

case "${1}" in
	"bootstrap" | "test" | "clean "| "chkenv ")
		source "${SCRIPTS_PATH}/${1}.sh"
		;;
	"--help" | "-h")
		usage
		;;
	*)
		>&2 echo "Command not found '${1}'"
		usage
		exit 1
esac
